name: Build Docker images
run-name: Build Docker images for ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RavenDB Version'
        required: true
        type: string
      triggering_build_number:
        description: 'Teamcity triggering build number'
        required: true
        type: string
      docker_user:
        description: 'DockerHub username'
        required: false
        type: string
        default: ravendb

env:
  IS_STABLE: ${{ ! contains(inputs.version, '-') }}
  IS_NIGHTLY: ${{ contains(inputs.version, 'nightly') }}
  DOCKER_USER: ${{ inputs.docker_user }}
  DOCKER_REPO: '${{ inputs.docker_user }}/ravendb'

jobs:
  debPackage:
    strategy:
      matrix:
        arch: [ x64, arm32v7, arm64v8 ]
        ubuntuName: [bionic, focal, jammy]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Get ravendb majorminor version & set repo
        run: |
          v=$(echo ${{ inputs.version }} | cut -d. -f1,2)
          echo "RAVEN_MAJOR_MINOR=$v" >> $GITHUB_ENV
          [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV
          buildType=$(echo ${{ inputs.version }} | cut -d- -f2)
          echo "TRIGGERING_BUILD_TYPE=$buildType" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3
        with:
          repository: 'ravendb/ravendb'
          ref: "v${{ env.RAVEN_MAJOR_MINOR }}"

      - name: Download tar package
        run: |
          case "${{ matrix.arch }}" in
            "arm32v7")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-raspberry-pi.tar.bz2"
              ;;
            "arm64v8")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-linux-arm64.tar.bz2"
              ;;

            "x64")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-linux-x64.tar.bz2"
              ;;
            *)
              echo "Unsupported architecture"
              exit 1
              ;;
          esac
          wget -P "temp" "$downloadURL"
        working-directory: scripts/linux/pkg/deb

      - name: Build deb package
        run: |
          chmod a+x *.sh
          case "${{ matrix.arch }}" in
            "arm32v7")
              arch="armhf"
              ;;
            "arm64v8")
              arch="arm64"
              ;;
            "x64")
              arch="amd64"
              ;;
            *)
              echo "Unsupported architecture"
              exit 1
              ;;
          esac
          source ./set-ubuntu-${{ matrix.ubuntuName }}.sh
          source ./set-raven-platform-${arch}.sh
          ./build-deb.sh
          echo "UBUNTU_VERSION=$DISTRO_VERSION" >> $GITHUB_ENV
        working-directory: scripts/linux/pkg/deb
        env:
          RAVENDB_VERSION: ${{ inputs.version }}

      - name: Upload deb package to artficats
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.ubuntuName }}-${{ matrix.arch }}
          path: scripts/linux/pkg/deb/dist/${{ env.UBUNTU_VERSION }}/ravendb*.deb

      - name: Upload deb package to s3
        run: |
          set -e
          set -x
          export DRY_RUN=1

          PACKAGES_DIST_DIR=scripts/linux/pkg/deb/dist

          ls -R $PACKAGES_DIST_DIR

          if [ "${{ env.IS_NIGHTLY }}" == "true" ]; then

            NIGHTLY_VERSION_DATE_PART=$(date "+%Y%M%d-%H%m" -u)
            export BUILD_VERSION="$NIGHTLY_VERSION_DATE_PART-Nightly"
          elif [ "${{ env.IS_STABLE }}" == "true" ]; then
            export BUILD_VERSION="${{ inputs.triggering_build_number }}"
          else
            export BUILD_VERSION="${{ inputs.triggering_build_number }}-${{ env.TRIGGERING_BUILD_TYPE }}"
          fi

          export COMMENT="RavenDB_${RAVENDB_VERSION}_DEB"
          export S3UPLOADER="./s3uploader.sh"

          # "$S3UPLOADER" --category "RavenDB for Ubuntu ${{ env.UBUNTU_VERSION }} ${{ matrix.arch }} DEB"   --filename "${PACKAGES_DIST_DIR}/${{ env.UBUNTU_VERSION }}/ravendb_${RAVENDB_VERSION}-0_ubuntu.${{ env.UBUNTU_VERSION }}_${{ matrix.arch }}.deb"
        env:
          RAVENDB_VERSION: ${{ inputs.version }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_PASS: ${{ secrets.SECRET_PASS }}

  linux:
    strategy:
      matrix:
        arch: [ x64, arm32v7, arm64v8 ]
      fail-fast: false
    runs-on: ubuntu-latest
    needs: debPackage
    steps:
      - name: Get ravendb majorminor version & set repo
        run: |
          v=$(echo ${{ inputs.version }} | cut -d. -f1,2)
          echo "RAVEN_MAJOR_MINOR=$v" >> $GITHUB_ENV
          [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          repository: 'hiddenshadow21/ravendb'
          ref: "v${{ env.RAVEN_MAJOR_MINOR }}"

      - uses: actions/download-artifact@v3
        with:
          name: package-focal-${{ matrix.arch }}
          path: downloads

      - name: Move artifacts to correct folder
        run: |
          chmod -v a+rw ravendb*.deb
          mv -v ravendb*.deb ../docker/ravendb-ubuntu/
        working-directory: downloads

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build image
        run: |
          case "${{ matrix.arch }}" in
            "arm32v7")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-raspberry-pi.tar.bz2"
              ;;
            "arm64v8")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-linux-arm64.tar.bz2"
              ;;

            "x64")
              downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-linux-x64.tar.bz2"
              ;;
            *)
              echo "Unsupported architecture"
              exit 1
              ;;
          esac
          wget -P "../artifacts" "$downloadURL"
          
          pwsh build-ubuntu.ps1 -Repo $DOCKER_REPO -Arch ${{ matrix.arch }}
        working-directory: docker

      - name: Publish package
        run: |
          pwsh publish-ubuntu.ps1 -Repo $DOCKER_REPO -Arch ${{ matrix.arch }}
          docker logout
        working-directory: docker

  windowsDockerImageBuilder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create.outputs.matrix }}
    steps:
      - name: Create Matrix
        id: create
        run: |
          v=$(echo ${{ inputs.version }} | cut -d. -f1,2)
          if [[ "$v" < "5.4" ]]; then
            echo "matrix=[ { \"os\": \"2019\", \"winVer\": \"1809\"} ]" >> "$GITHUB_OUTPUT"
          else
            echo "matrix=[ { \"os\": \"2019\", \"winVer\": \"1809\"}, { \"os\": \"2022\", \"winVer\": \"ltsc2022\"} ]" >> "$GITHUB_OUTPUT"
          fi

  windows:
    needs: windowsDockerImageBuilder
    strategy:
      matrix:
        data: ${{ fromJson(needs.windowsDockerImageBuilder.outputs.matrix) }}
      fail-fast: false
    runs-on: windows-${{ matrix.data.os }}
    steps:
      - name: Get ravendb majorminor version & set repo
        shell: bash
        run: |
          v=$(echo ${{ inputs.version }} | cut -d. -f1,2)
          echo "RAVEN_MAJOR_MINOR=$v" >> $GITHUB_ENV
          [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV

      - name: Login to docker
        shell: pwsh
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: actions/checkout@v3
        with:
          repository: 'ravendb/ravendb'
          ref: "v${{ env.RAVEN_MAJOR_MINOR }}"

      - name: Download package
        shell: pwsh
        run: |
          $downloadURL="https://daily-builds.s3.amazonaws.com/RavenDB-${{ inputs.version }}-windows-x64.zip"
          mkdir artifacts
          Invoke-WebRequest -Uri "$downloadURL" -OutFile "artifacts\RavenDB-${{ inputs.version }}-windows-x64.zip"

      - name: Build image
        shell: pwsh
        run: |
          & .\build-nanoserver.ps1 -Repo ${{ env.DOCKER_REPO }} -WinVer ${{ matrix.data.winVer }}
        working-directory: docker

      - name: Publish package
        shell: pwsh
        run: |
          & .\publish-nanoserver.ps1 -Repo ${{ env.DOCKER_REPO }} -WinVer ${{ matrix.data.winVer }}
          docker logout
        working-directory: docker
