name: Docker Create mutiarch manifest
on:
  workflow_call:
    inputs:
      version:
        description: 'RavenDB Version'
        required: true
        type: string
      docker_user:
        description: 'DockerHub username'
        required: false
        type: string
        default: hiddenshadow21
      github_repository:
        description: 'Github repository'
        required: false
        type: string
        default: hiddenshadow21/ravendb
      deb_only:
        description: 'Build deb packages only'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Dry run'
        required: false
        type: string
        default: ''

env:
  IS_STABLE: ${{ ! contains(inputs.version, '-') }}
  IS_NIGHTLY: ${{ contains(inputs.version, 'nightly') }}
  DOCKER_USER: ${{ inputs.docker_user }}
  DOCKER_REPO: '${{ inputs.docker_user }}/ravendb'
  DRY_RUN: ${{ inputs.dry_run }}

jobs:
  multiarch:
    name: Create docker multiarch manifest
    runs-on: ubuntu-latest
    if: inputs.deb_only == false
    steps:
      - name: Get ravendb majorminor version & set repo
        shell: bash
        run: |
          v=$(echo ${{ inputs.version }} | cut -d. -f1,2)
          echo "RAVEN_MAJOR_MINOR=$v" >> $GITHUB_ENV
          [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV

      - name: Login to docker
        shell: pwsh
        run: |
          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: actions/checkout@v3
        with:
          repository: '${{ inputs.github_repository }}'
          ref: "v${{ env.RAVEN_MAJOR_MINOR }}"

      - name: Publish multiarch
        shell: pwsh
        run: |
          & .\publish-multiarch.ps1 -Repo ${{ env.DOCKER_REPO }}
          docker logout
        working-directory: docker