name: Test Deb package

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      github_repository:
        type: string
        required: false
        default: hiddenshadow21/ravendb
      deb_only:
        type: boolean
        required: false
        default: false
      

jobs:
  test-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DISTRO_VERSION_NAME: ["focal", "jammy", "noble"]
        arch: [x64, arm32v7, arm64v8]
  
    steps:
      - uses: actions/checkout@v3
        with:
          repository: '${{ inputs.github_repository }}'
          ref: "v${{ env.RAVEN_MAJOR_MINOR }}"
          path: ravendb

      - name: Get docker system
        run: |
          dockerSystem=$(grep -o -P "(?<=FROM\smcr\.microsoft\.com\/dotnet\/runtime-deps:\d\.\d-)([a-zA-Z]+)(?=.*)" Dockerfile.${{ matrix.arch }})
          echo "DOCKER_SYSTEM=$dockerSystem" >> $GITHUB_ENV
        working-directory: ravendb/docker/ravendb-ubuntu

      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package-${{ env.DOCKER_SYSTEM }}-${{ matrix.arch }}
          path: ./deb

      - name: Run x64 package tests
        if: matrix.arch == 'x64'
        run: ./test.sh
        working-directory: "tests"

      - name: Run multiarch package tests
        if: matrix.arch != 'x64'
        run: ./test.sh
        working-directory: "tests"